// <auto-generated />
using System;
using BlissQuestions.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlissQuestions.API.Migrations
{
    [DbContext(typeof(QuestionInfoDbContext))]
    [Migration("20230111124029_CreatingDB")]
    partial class CreatingDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.13");

            modelBuilder.Entity("BlissQuestions.API.Models.ChoiceDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Choice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Votes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Choices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Choice = "Swift",
                            QuestionId = 1,
                            Votes = 2048
                        },
                        new
                        {
                            Id = 2,
                            Choice = "Python",
                            QuestionId = 1,
                            Votes = 1024
                        },
                        new
                        {
                            Id = 3,
                            Choice = "Objective-C",
                            QuestionId = 1,
                            Votes = 512
                        },
                        new
                        {
                            Id = 4,
                            Choice = "Ruby",
                            QuestionId = 1,
                            Votes = 256
                        },
                        new
                        {
                            Id = 5,
                            Choice = "Swift",
                            QuestionId = 2,
                            Votes = 2048
                        },
                        new
                        {
                            Id = 6,
                            Choice = "Python",
                            QuestionId = 2,
                            Votes = 1024
                        },
                        new
                        {
                            Id = 7,
                            Choice = "Objective-C",
                            QuestionId = 2,
                            Votes = 512
                        },
                        new
                        {
                            Id = 8,
                            Choice = "Ruby",
                            QuestionId = 2,
                            Votes = 256
                        },
                        new
                        {
                            Id = 9,
                            Choice = "Swift",
                            QuestionId = 3,
                            Votes = 2048
                        },
                        new
                        {
                            Id = 10,
                            Choice = "Python",
                            QuestionId = 3,
                            Votes = 1024
                        },
                        new
                        {
                            Id = 11,
                            Choice = "Objective-C",
                            QuestionId = 3,
                            Votes = 512
                        },
                        new
                        {
                            Id = 12,
                            Choice = "Ruby",
                            QuestionId = 3,
                            Votes = 256
                        },
                        new
                        {
                            Id = 13,
                            Choice = "Swift",
                            QuestionId = 4,
                            Votes = 2048
                        },
                        new
                        {
                            Id = 14,
                            Choice = "Python",
                            QuestionId = 4,
                            Votes = 1024
                        },
                        new
                        {
                            Id = 15,
                            Choice = "Objective-C",
                            QuestionId = 4,
                            Votes = 512
                        },
                        new
                        {
                            Id = 16,
                            Choice = "Ruby",
                            QuestionId = 4,
                            Votes = 256
                        },
                        new
                        {
                            Id = 17,
                            Choice = "Swift",
                            QuestionId = 5,
                            Votes = 2048
                        },
                        new
                        {
                            Id = 18,
                            Choice = "Python",
                            QuestionId = 5,
                            Votes = 1024
                        },
                        new
                        {
                            Id = 19,
                            Choice = "Objective-C",
                            QuestionId = 5,
                            Votes = 512
                        },
                        new
                        {
                            Id = 20,
                            Choice = "Ruby",
                            QuestionId = 5,
                            Votes = 256
                        },
                        new
                        {
                            Id = 21,
                            Choice = "Swift",
                            QuestionId = 6,
                            Votes = 2048
                        },
                        new
                        {
                            Id = 22,
                            Choice = "Python",
                            QuestionId = 6,
                            Votes = 1024
                        },
                        new
                        {
                            Id = 23,
                            Choice = "Objective-C",
                            QuestionId = 6,
                            Votes = 512
                        },
                        new
                        {
                            Id = 24,
                            Choice = "Ruby",
                            QuestionId = 6,
                            Votes = 256
                        },
                        new
                        {
                            Id = 25,
                            Choice = "Swift",
                            QuestionId = 7,
                            Votes = 2048
                        },
                        new
                        {
                            Id = 26,
                            Choice = "Python",
                            QuestionId = 7,
                            Votes = 1024
                        },
                        new
                        {
                            Id = 27,
                            Choice = "Objective-C",
                            QuestionId = 7,
                            Votes = 512
                        },
                        new
                        {
                            Id = 28,
                            Choice = "Ruby",
                            QuestionId = 7,
                            Votes = 256
                        },
                        new
                        {
                            Id = 29,
                            Choice = "Swift",
                            QuestionId = 8,
                            Votes = 2048
                        },
                        new
                        {
                            Id = 30,
                            Choice = "Python",
                            QuestionId = 8,
                            Votes = 1024
                        },
                        new
                        {
                            Id = 31,
                            Choice = "Objective-C",
                            QuestionId = 8,
                            Votes = 512
                        },
                        new
                        {
                            Id = 32,
                            Choice = "Ruby",
                            QuestionId = 8,
                            Votes = 256
                        },
                        new
                        {
                            Id = 33,
                            Choice = "Swift",
                            QuestionId = 9,
                            Votes = 2048
                        },
                        new
                        {
                            Id = 34,
                            Choice = "Python",
                            QuestionId = 9,
                            Votes = 1024
                        },
                        new
                        {
                            Id = 35,
                            Choice = "Objective-C",
                            QuestionId = 9,
                            Votes = 512
                        },
                        new
                        {
                            Id = 36,
                            Choice = "Ruby",
                            QuestionId = 9,
                            Votes = 256
                        },
                        new
                        {
                            Id = 37,
                            Choice = "Swift",
                            QuestionId = 10,
                            Votes = 2048
                        },
                        new
                        {
                            Id = 38,
                            Choice = "Python",
                            QuestionId = 10,
                            Votes = 1024
                        },
                        new
                        {
                            Id = 39,
                            Choice = "Objective-C",
                            QuestionId = 10,
                            Votes = 512
                        },
                        new
                        {
                            Id = 40,
                            Choice = "Ruby",
                            QuestionId = 10,
                            Votes = 256
                        });
                });

            modelBuilder.Entity("BlissQuestions.API.Models.QuestionDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://dummyimage.com/600x400/000/fff.png&text=question+1+image+(600x400)",
                            PublishedAt = new DateTime(2015, 8, 5, 8, 40, 51, 620, DateTimeKind.Unspecified),
                            Question = "Favorite programming language?",
                            ThumbUrl = "https://dummyimage.com/120x120/000/fff.png&text=question+1+image+(120x120)"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://dummyimage.com/600x400/000/fff.png&text=question+1+image+(600x400)",
                            PublishedAt = new DateTime(2015, 8, 5, 8, 40, 51, 620, DateTimeKind.Unspecified),
                            Question = "Favorite programming language?",
                            ThumbUrl = "https://dummyimage.com/120x120/000/fff.png&text=question+1+image+(120x120)"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://dummyimage.com/600x400/000/fff.png&text=question+1+image+(600x400)",
                            PublishedAt = new DateTime(2015, 8, 5, 8, 40, 51, 620, DateTimeKind.Unspecified),
                            Question = "Favorite programming language?",
                            ThumbUrl = "https://dummyimage.com/120x120/000/fff.png&text=question+1+image+(120x120)"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://dummyimage.com/600x400/000/fff.png&text=question+1+image+(600x400)",
                            PublishedAt = new DateTime(2015, 8, 5, 8, 40, 51, 620, DateTimeKind.Unspecified),
                            Question = "Favorite programming language?",
                            ThumbUrl = "https://dummyimage.com/120x120/000/fff.png&text=question+1+image+(120x120)"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://dummyimage.com/600x400/000/fff.png&text=question+1+image+(600x400)",
                            PublishedAt = new DateTime(2015, 8, 5, 8, 40, 51, 620, DateTimeKind.Unspecified),
                            Question = "Favorite programming language?",
                            ThumbUrl = "https://dummyimage.com/120x120/000/fff.png&text=question+1+image+(120x120)"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "https://dummyimage.com/600x400/000/fff.png&text=question+1+image+(600x400)",
                            PublishedAt = new DateTime(2015, 8, 5, 8, 40, 51, 620, DateTimeKind.Unspecified),
                            Question = "Favorite programming language?",
                            ThumbUrl = "https://dummyimage.com/120x120/000/fff.png&text=question+1+image+(120x120)"
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "https://dummyimage.com/600x400/000/fff.png&text=question+1+image+(600x400)",
                            PublishedAt = new DateTime(2015, 8, 5, 8, 40, 51, 620, DateTimeKind.Unspecified),
                            Question = "Favorite programming language?",
                            ThumbUrl = "https://dummyimage.com/120x120/000/fff.png&text=question+1+image+(120x120)"
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "https://dummyimage.com/600x400/000/fff.png&text=question+1+image+(600x400)",
                            PublishedAt = new DateTime(2015, 8, 5, 8, 40, 51, 620, DateTimeKind.Unspecified),
                            Question = "Favorite programming language?",
                            ThumbUrl = "https://dummyimage.com/120x120/000/fff.png&text=question+1+image+(120x120)"
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "https://dummyimage.com/600x400/000/fff.png&text=question+1+image+(600x400)",
                            PublishedAt = new DateTime(2015, 8, 5, 8, 40, 51, 620, DateTimeKind.Unspecified),
                            Question = "Favorite programming language?",
                            ThumbUrl = "https://dummyimage.com/120x120/000/fff.png&text=question+1+image+(120x120)"
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "https://dummyimage.com/600x400/000/fff.png&text=question+1+image+(600x400)",
                            PublishedAt = new DateTime(2015, 8, 5, 8, 40, 51, 620, DateTimeKind.Unspecified),
                            Question = "Favorite programming language?",
                            ThumbUrl = "https://dummyimage.com/120x120/000/fff.png&text=question+1+image+(120x120)"
                        });
                });

            modelBuilder.Entity("BlissQuestions.API.Models.ChoiceDto", b =>
                {
                    b.HasOne("BlissQuestions.API.Models.QuestionDto", "Question")
                        .WithMany("Choices")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("BlissQuestions.API.Models.QuestionDto", b =>
                {
                    b.Navigation("Choices");
                });
#pragma warning restore 612, 618
        }
    }
}
